version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: etim-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  mcp-server:
    build: .
    container_name: etim-mcp-server
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ETIM_CLIENT_ID=${ETIM_CLIENT_ID}
      - ETIM_CLIENT_SECRET=${ETIM_CLIENT_SECRET}
      - ETIM_AUTH_URL=https://etimauth.etim-international.com
      - ETIM_API_URL=https://etimapi.etim-international.com
      - ETIM_DEFAULT_LANGUAGE=EN
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - CACHE_TTL=3600
      - CACHE_CLASS_TTL=86400
      - CACHE_LANGUAGES_TTL=604800
      - LOG_LEVEL=INFO
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
